version: 2
jobs:
  python_2:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - checkout
      - run: 
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python2.7/site-packages
      - restore_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
            pip install codecov
      - save_cache:
          key: deps2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python2.7/site-packages"
      - run: coverage run --include=auth0/v3/*.py --omit=auth0/v3/test/*.py -m unittest discover
      - run:
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)
  python_3:
    docker:
      - image: circleci/python:3.6-jessie
    steps:
      - checkout
      - run: 
          command: |
            sudo chown -R circleci:circleci /usr/local/bin
            sudo chown -R circleci:circleci /usr/local/lib/python3.6/site-packages
      - restore_cache:
          key: deps3-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            pip install -r requirements.txt
            pip install codecov
      - save_cache:
          key: deps3-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ".venv"
            - "/usr/local/bin"
            - "/usr/local/lib/python3.6/site-packages"
      - run: coverage run --include=auth0/v3/*.py --omit=auth0/v3/test/*.py -m unittest discover
      - run:
          when: on_success
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  build:
    jobs:
      - python_2
      - python_3